version: '3.9'
services:
  lara_php:
    build: ./docker/php
    working_dir: '/var/www/domains'
    networks:
      - project_network
    volumes:
      - ./project:/var/www/domains/project:cached
    expose:
      - 9000

  lara_nginx:
    image: nginx:1.21.1
    networks:
      - project_network
    volumes:
      - ./project:/var/www/domains/project:cached
      - ./docker/nginx:/etc/nginx/conf.d:cached
    ports:
      - "127.0.0.1:8080:80"

  lara_cron:
    build: ./docker/cron
    working_dir: /var/www/domains
    networks:
      - project_network
    volumes:
      - ./project:/var/www/domains/project:cached

  lara_mysql:
    image: "mysql/mysql-server:8.0"
    volumes:
      - laravel_db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password && --character-set-server=utf8mb3_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    expose:
      - 3306
    networks:
      - project_network

  lara_edis:
    image: redis
    expose:
      - 6379
    networks:
      - project_network
    volumes:
      - laravel_redis_db:/data:cached

  lara_adminer:
    image: adminer
    restart: always
    ports:
      - "127.0.0.1:8081:8080"
    networks:
      - project_network
    environment:
      ADMINER_DESIGN: haeckel
      ADMINER_DEFAULT_SERVER: g-mysql

networks:
  project_network:
    driver: bridge


volumes:
  laravel_db:
    external: true
  laravel_redis_db:
    external: true
