
services:
  php:
    build: ./docker/php
    working_dir: '/var/www/domains'
    networks:
      - project_network
    volumes:
      - ./project:/var/www/domains/project:cached
    expose:
      - 9000

  nginx:
    image: nginx:1.21.1
    networks:
      - ${NETWORK}
    volumes:
      - ./project:/var/www/domains/project:cached
      - ./docker/nginx:/etc/nginx/conf.d:cached
    ports:
      - "127.0.0.1:8080:80"

  mysql:
    image: "mysql/mysql-server:8.0"
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password && --character-set-server=utf8mb3_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    expose:
      - 3306
    networks:
      - ${NETWORK}

  redis:
    image: redis
    expose:
      - 6379
    networks:
      - ${NETWORK}
    volumes:
      - ${REDIS_VOLUME}:/data:cached

  adminer:
    image: adminer
    ports:
      - "127.0.0.1:8081:8080"
    networks:
      - ${NETWORK}
    environment:
      ADMINER_DESIGN: haeckel
      ADMINER_DEFAULT_SERVER: laravel-template-mysql-1

networks:
  project_network:
    driver: bridge


volumes:
  laravel-template-db:
    external: true
  laravel-template-redis-db:
    external: true
